jwt:
  secret-key: ec6a8f55ea449220a01f8753f251392a2afae71105887f0535f5d9e49e317096bb8a7d4256b5cdc1c6532f64364a45a8872ac3c32d6d406e9237e4fc036d5352

oauth:
  kakao:
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    grant-type: authorization_code
    client-id: 4dc46ddb4905d21f0b32d6640e058a74
    redirect-uri: http://localhost:8080/member/kakao

cap:
  key: cap123

#mail:
#  host: smtp.gmail.com
#  port: 587
#  username: testaddressbaek@gmail.com
#  password: @@qwer1234
#  properties:
#    mail.smtp.auth: true
#    mail.smtp.starttls.enable: true

#mail:
#  host: smtp.gmail.com # 1
#  port: 587 # 2
#  username: testaddressbaek # 3
#  password: zhldimoyahsihgmf # 4
#  properties:
#    mail:
#      smtp:
#        auth: true # 5
#        timeout: 5000 # 6
#        starttls:
#          enable: true